apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: k8s-multi-com-tls
  namespace: udemy-course
spec:
  secretName: udemy-course-secret
  issuerRef:
    name: letsencrypt-prod
  commonName: awesomecloudservice.digital
  dnsNames:
  - awesomecloudservice.digital
  - www.awesomecloudservice.digital